In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

df = pd.read_excel('Data/data.xlsx')

In [2]:
df.head()

Unnamed: 0      ID   Salary        DOJ                  DOL  \
0      train  203097   420000 2012-06-01              present   
1      train  579905   500000 2013-09-01              present   
2      train  810601   325000 2014-06-01              present   
3      train  267447  1100000 2011-07-01              present   
4      train  343523   200000 2014-03-01  2015-03-01 00:00:00   

                Designation    JobCity Gender        DOB  10percentage  \
0   senior quality engineer  Bangalore      f 1990-02-19          84.3   
1         assistant manager     Indore      m 1989-10-04          85.4   
2          systems engineer    Chennai      f 1992-08-03          85.0   
3  senior software engineer    Gurgaon      m 1989-12-05          85.6   
4                       get    Manesar      m 1991-02-27          78.0   

                          10board  12graduation  12percentage  \
0  board ofsecondary education,ap          2007          95.8   
1                            cbse          2007          85.0   
2                            cbse          2010          68.2   
3                            cbse          2007          83.6   
4                            cbse          2008          76.8   

                              12board  CollegeID  CollegeTier       Degree  \
0  board of intermediate education,ap       1141            2  B.Tech/B.E.   
1                                cbse       5807            2  B.Tech/B.E.   
2                                cbse         64            2  B.Tech/B.E.   
3                                cbse       6920            1  B.Tech/B.E.   
4                                cbse      11368            2  B.Tech/B.E.   

                              Specialization  collegeGPA  CollegeCityID  \
0                       computer engineering       78.00           1141   
1  electronics and communication engineering       70.06           5807   
2                     information technology       70.00             64   
3                       computer engineering       74.64           6920   
4  electronics and communication engineering       73.90          11368   

   CollegeCityTier    CollegeState  GraduationYear  English  Logical  Quant  \
0                0  Andhra Pradesh            2011      515      585    525   
1                0  Madhya Pradesh            2012      695      610    780   
2                0   Uttar Pradesh            2014      615      545    370   
3                1           Delhi            2011      635      585    625   
4                0   Uttar Pradesh            2012      545      625    465   

     Domain  ComputerProgramming  ElectronicsAndSemicon  ComputerScience  \
0  0.635979                  445                     -1               -1   
1  0.960603                   -1                    466               -1   
2  0.450877                  395                     -1               -1   
3  0.974396                  615                     -1               -1   
4  0.124502                   -1                    233               -1   

   MechanicalEngg  ElectricalEngg  TelecomEngg  CivilEngg  conscientiousness  \
0              -1              -1           -1         -1             0.9737   
1              -1              -1           -1         -1            -0.7335   
2              -1              -1           -1         -1             0.2718   
3              -1              -1           -1         -1             0.0464   
4              -1              -1           -1         -1            -0.8810   

   agreeableness  extraversion  nueroticism  openess_to_experience  
0         0.8128        0.5269      1.35490                -0.4455  
1         0.3789        1.2396     -0.10760                 0.8637  
2         1.7109        0.1637     -0.86820                 0.6721  
3         0.3448       -0.3440     -0.40780                -0.9194  
4        -0.2793       -1.0697      0.09163                -0.1295

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3998 entries, 0 to 3997
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Unnamed: 0             3998 non-null   object        
 1   ID                     3998 non-null   int64         
 2   Salary                 3998 non-null   int64         
 3   DOJ                    3998 non-null   datetime64[ns]
 4   DOL                    3998 non-null   object        
 5   Designation            3998 non-null   object        
 6   JobCity                3998 non-null   object        
 7   Gender                 3998 non-null   object        
 8   DOB                    3998 non-null   datetime64[ns]
 9   10percentage           3998 non-null   float64       
 10  10board                3998 non-null   object        
 11  12graduation           3998 non-null   int64         
 12  12percentage           3998 non-null   float64       
 13  12b

In [4]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, ID, Salary, DOJ, DOL, Designation, JobCity, Gender, DOB, 10percentage, 10board, 12graduation, 12percentage, 12board, CollegeID, CollegeTier, Degree, Specialization, collegeGPA, CollegeCityID, CollegeCityTier, CollegeState, GraduationYear, English, Logical, Quant, Domain, ComputerProgramming, ElectronicsAndSemicon, ComputerScience, MechanicalEngg, ElectricalEngg, TelecomEngg, CivilEngg, conscientiousness, agreeableness, extraversion, nueroticism, openess_to_experience]
Index: []

In [5]:
df['Designation'].str.strip()
df['Designation'] = df['Designation'].str.capitalize()

In [6]:
df['Designation'].value_counts()

Designation
Software engineer                         539
Software developer                        265
System engineer                           205
Programmer analyst                        139
Systems engineer                          118
Java software engineer                    111
Software test engineer                    100
Project engineer                           77
Technical support engineer                 76
Senior software engineer                   72
Java developer                             67
Test engineer                              57
Web developer                              54
Application developer                      52
Assistant manager                          52
Network engineer                           51
Data analyst                               49
Business analyst                           49
Engineer                                   47
Android developer                          46
Associate software engineer                46
Programmer            

In [7]:
df['JobCity'] = df['JobCity'].str.strip()
df['JobCity'] = df['JobCity'].str.capitalize()

In [8]:
choices = ['Bangalore','Noida','Hyderabad','Pune','Chennai','Gurgaon','Delhi','Kolkata','Mumbai','Jaipur',
           'Lucknow','Mysore','Mumbai','Noida','Chandigarh','Bhubaneswar','Indore','Coimbatore','Bhopal','Ahmedabad','Faridabad',
           'Ghaziabad','Kochi','Mohali','Dehradun','Nagpur','Mangalore','Trivandrum','Kanpur','Thane','Jabalpur','Patna','Visakhapatnam',
           'Pondicherry','Trichy','Raipur','Jodhpur','Meerut','Udaipur','Ranchi','Madurai','Nasikcity','Bilaspur','Dubai',
           'Rudrapur','Panchkula','Haridwar','Ludhiana','Tirupathi','Gandhinagar','Secunderabad','Aurangabad']

In [9]:
df['JobCity'].value_counts()

JobCity
Bangalore                                 665
Noida                                     389
Hyderabad                                 368
Pune                                      327
Chennai                                   313
Gurgaon                                   217
New delhi                                 204
Kolkata                                   119
Mumbai                                    119
Jaipur                                     53
Lucknow                                    41
Mysore                                     40
Navi mumbai                                34
Greater noida                              29
Chandigarh                                 28
Bhubaneswar                                27
Indore                                     25
Delhi                                      21
Coimbatore                                 21
Bhopal                                     19
Ahmedabad                                  19
Faridabad                 

In [10]:
df['JobCity'].value_counts()

JobCity
Bangalore                                 665
Noida                                     389
Hyderabad                                 368
Pune                                      327
Chennai                                   313
Gurgaon                                   217
New delhi                                 204
Kolkata                                   119
Mumbai                                    119
Jaipur                                     53
Lucknow                                    41
Mysore                                     40
Navi mumbai                                34
Greater noida                              29
Chandigarh                                 28
Bhubaneswar                                27
Indore                                     25
Delhi                                      21
Coimbatore                                 21
Bhopal                                     19
Ahmedabad                                  19
Faridabad                 

In [11]:
from fuzzywuzzy import process

def spell_check(target='', choice=[],threashold=65):
    word, theres = process.extractOne(target,choice)
    if theres >= threashold:
        return word
    else:
        return 'Other'

In [12]:
df['JobCity2'] = df['JobCity'].apply(lambda x: spell_check(str(x),choices))

In [13]:
df['JobCity'].unique()

array(['Bangalore', 'Indore', 'Chennai', 'Gurgaon', 'Manesar',
       'Hyderabad', 'Banglore', 'Noida', 'Kolkata', 'Pune', nan, 'Mohali',
       'Jhansi', 'Delhi', 'Bhubaneswar', 'Navi mumbai', 'Mumbai',
       'New delhi', 'Mangalore', 'Rewari', 'Gaziabaad', 'Bhiwadi',
       'Mysore', 'Rajkot', 'Greater noida', 'Jaipur', 'Thane',
       'Maharajganj', 'Thiruvananthapuram', 'Punchkula', 'Bhubaneshwar',
       'Coimbatore', 'Dhanbad', 'Lucknow', 'Trivandrum', 'Gandhi nagar',
       'Una', 'Daman and diu', 'Gurgoan', 'Vsakhapttnam', 'Nagpur',
       'Bhagalpur', 'New delhi - jaisalmer', 'Ahmedabad', 'Kochi/cochin',
       'Bankura', 'Bengaluru', 'Kanpur', 'Vijayawada', 'Kochi', 'Beawar',
       'Alwar', 'Siliguri', 'Raipur', 'Bhopal', 'Faridabad', 'Jodhpur',
       'Udaipur', 'Muzaffarpur', 'Kolkata`', 'Bulandshahar', 'Haridwar',
       'Raigarh', 'Visakhapatnam', 'Jabalpur', 'Unnao', 'Aurangabad',
       'Belgaum', 'Dehradun', 'Rudrapur', 'Jamshedpur', 'Vizag', 'Nouda',
       'Dharams

In [14]:
df['JobCity'].value_counts()

JobCity
Bangalore                                 665
Noida                                     389
Hyderabad                                 368
Pune                                      327
Chennai                                   313
Gurgaon                                   217
New delhi                                 204
Kolkata                                   119
Mumbai                                    119
Jaipur                                     53
Lucknow                                    41
Mysore                                     40
Navi mumbai                                34
Greater noida                              29
Chandigarh                                 28
Bhubaneswar                                27
Indore                                     25
Delhi                                      21
Coimbatore                                 21
Bhopal                                     19
Ahmedabad                                  19
Faridabad                 

In [15]:
df['JobCity'].isnull().sum()

461

In [16]:
df['Gender'].value_counts()

Gender
m    3041
f     957
Name: count, dtype: int64

In [17]:
maxdate = '2015-12-12 00:00:00'

In [18]:
df['DOL'] = pd.to_datetime(df['DOL'].replace('present',maxdate))

In [19]:
df['YOE'] = round((df['DOL']-df['DOJ'])/pd.Timedelta(days=365))

In [20]:
df['YOE'] = df['YOE'].where(df['YOE']>0,0)

In [21]:
df['YOE'] = df['YOE'].astype('int')

In [22]:
df['12graduation'].unique()

array([2007, 2010, 2008, 2009, 2006, 2011, 2005, 1995, 2004, 2012, 2003,
       2002, 2001, 1998, 2013, 1999], dtype=int64)

In [23]:
df['CollegeTier'].unique()

array([2, 1], dtype=int64)

In [24]:
def board(data):
    if ('cbs' in data.lower()) or ('central' in data.lower()):
        return 'CBSE'
    elif 'mat' in data.lower():
        return 'Matriculation'
    elif 'icse' in data.lower():
        return 'ICSE'
    else:
        return 'State Board'

In [25]:
df['10board'] = df['10board'].apply(lambda x: board(str(x)))

In [26]:
df['12board'] = df['12board'].apply(lambda x: board(str(x)))

In [27]:
df['Degree'].unique()

array(['B.Tech/B.E.', 'MCA', 'M.Tech./M.E.', 'M.Sc. (Tech.)'],
      dtype=object)

In [28]:
df['Specialization'].unique()

array(['computer engineering',
       'electronics and communication engineering',
       'information technology', 'computer science & engineering',
       'mechanical engineering', 'electronics and electrical engineering',
       'electronics & telecommunications',
       'instrumentation and control engineering', 'computer application',
       'electronics and computer engineering', 'electrical engineering',
       'applied electronics and instrumentation',
       'electronics & instrumentation eng',
       'information science engineering', 'civil engineering',
       'mechanical and automation', 'industrial & production engineering',
       'control and instrumentation engineering',
       'metallurgical engineering',
       'electronics and instrumentation engineering',
       'electronics engineering', 'ceramic engineering',
       'chemical engineering', 'aeronautical engineering', 'other',
       'biotechnology', 'embedded systems technology',
       'electrical and power engi

In [29]:
df['CollegeCityTier'].unique()

array([0, 1], dtype=int64)

In [30]:
df['CollegeState'].value_counts()

CollegeState
Uttar Pradesh        915
Karnataka            370
Tamil Nadu           367
Telangana            319
Maharashtra          262
Andhra Pradesh       225
West Bengal          196
Punjab               193
Madhya Pradesh       189
Haryana              180
Rajasthan            174
Orissa               172
Delhi                162
Uttarakhand          113
Kerala                33
Jharkhand             28
Chhattisgarh          27
Gujarat               24
Himachal Pradesh      16
Bihar                 10
Jammu and Kashmir      7
Assam                  5
Union Territory        5
Sikkim                 3
Meghalaya              2
Goa                    1
Name: count, dtype: int64

In [31]:
df.loc[df['GraduationYear']==0,['GraduationYear']] = 2014

In [32]:
df['GraduationYear'].unique()

array([2011, 2012, 2014, 2016, 2013, 2010, 2015, 2009, 2017, 2007],
      dtype=int64)

In [33]:
def age(dob):
    today = pd.to_datetime(maxdate)
    return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))

In [34]:
df['age'] = df['DOB'].apply(age)

In [35]:
df.drop(['Unnamed: 0','ID','DOJ','DOL','DOB','CollegeID','JobCity','CollegeCityID'],axis=1,inplace=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3998 entries, 0 to 3997
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Salary                 3998 non-null   int64  
 1   Designation            3998 non-null   object 
 2   Gender                 3998 non-null   object 
 3   10percentage           3998 non-null   float64
 4   10board                3998 non-null   object 
 5   12graduation           3998 non-null   int64  
 6   12percentage           3998 non-null   float64
 7   12board                3998 non-null   object 
 8   CollegeTier            3998 non-null   int64  
 9   Degree                 3998 non-null   object 
 10  Specialization         3998 non-null   object 
 11  collegeGPA             3998 non-null   float64
 12  CollegeCityTier        3998 non-null   int64  
 13  CollegeState           3998 non-null   object 
 14  GraduationYear         3998 non-null   int64  
 15  Engl

In [37]:
df.to_excel('Data/clean.xlsx',index=False)